# Generated by Django 5.2.9 on 2026-01-02 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_aiauditlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiauditlog',
            old_name='ai_analysis',
            new_name='ai_response',
        ),
        migrations.RenameField(
            model_name='aiauditlog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='aiauditlog',
            old_name='input_symptoms',
            new_name='input_query',
        ),
        migrations.RemoveField(
            model_name='aiauditlog',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='aiauditlog',
            name='model_used',
            field=models.CharField(default='gpt-4o-mini', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiauditlog',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='medical_records.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aiauditlog',
            name='agent_name',
            field=models.CharField(default='OmniCare_Analyst', max_length=100),
        ),
    ]
