# Generated by Django 5.2.9 on 2026-01-04 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_patient_doctor_alter_patient_clinical_history_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mensaje_usuario', models.TextField()),
                ('respuesta_ia', models.TextField()),
                ('dolor', models.IntegerField(default=0)),
                ('urgencia', models.IntegerField(default=0)),
                ('riesgo', models.IntegerField(default=0)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
